<?php

/*
  Plugin Name: Robots Meta Settings
  Plugin URI: https://wpsurfer.com/meta-robots-settings-without-plugin-wordpress/
  Description: Add Robots Meta Settings based on the info provided on a custom field.  Robots Meta Tags based on the SEO Framework plugin.
  Version: 1.0
  Author: TicoLibre
  Author URI: https://ticolibre.com
*/

// Exit if accessed directly
if (!defined('ABSPATH')) {
    exit;
}

// Filter to Remove Robots Meta Settings generated by Wordpress
remove_filter( 'wp_robots', 'wp_robots_max_image_preview_large' );

// Add Robots Meta Setting to Head
function custom_robots_meta_tags() {
    // Check if it's a singular post or page
    if (is_singular()) {
        // Get the custom field value
        $robots_meta_option = get_post_meta(get_the_ID(), 'robots_meta_settings', true);

        // Check if the custom field value exists and is not empty
        if (!empty($robots_meta_option)) {
            // Based on the value of the custom field, generate the appropriate meta tag
            switch ($robots_meta_option) {
                case 'robots_meta_option_01':
                    echo "<meta name=\"robots\" content=\"max-snippet:-1,max-image-preview:large,max-video-preview:-1\" />\n";
                    break;
                case 'robots_meta_option_02':
                    echo "<meta name=\"robots\" content=\"noindex,max-snippet:-1,max-image-preview:large,max-video-preview:-1\" />\n";
                    break;
                case 'robots_meta_option_03':
                    echo "<meta name=\"robots\" content=\"nofollow,max-snippet:-1,max-image-preview:large,max-video-preview:-1\" />\n";
                    break;
                case 'robots_meta_option_04':
                    echo "<meta name=\"robots\" content=\"noindex,nofollow,max-snippet:-1,max-image-preview:large,max-video-preview:-1\" />\n";
                    break;
                default:
                    // Default meta tag if the custom field value is not recognized
                    echo "<meta name=\"robots\" content=\"max-snippet:-1,max-image-preview:large,max-video-preview:-1\" />\n";
                    break;
            }
        } else {
            // Default meta tag if the custom field value is empty or not set
            echo "<meta name=\"robots\" content=\"max-snippet:-1,max-image-preview:large,max-video-preview:-1\" />\n";
        }
    }
}

// Hook into wp_head to insert the meta tags with priority 1
add_action('wp_head', 'custom_robots_meta_tags', 1);
